[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Configure partition table to include FAT filesystem (FFat)
board_build.partitions = partitions_1m_app_7m_ffat.csv
board_build.filesystem = fatfs

; Debugging over Serial
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Optional: Increase Core Debug Level to see HTTPS handshake logs
;build_type = debug
;build_flags = 
;    -D CORE_DEBUG_LEVEL=5

; Add ArduinoJson for REST API handling
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

